using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

/// <summary>Store Builder UI logic. The widgets are generated by Tools/Sari/Store Builder UI/Rebuild UI.</summary>
public partial class SB_UIHandler : MonoBehaviour
{
    [Serializable]
    public struct ToolButton
    {
        public BuilderTool tool;
        public Button button;
        public SB_ButtonFx fx;
    }

    [Header("References")]
    public SB_InteractionController interactionController;

    [Header("Top Bar")]
    public TMP_InputField storeNameInput;
    public GameObject unsavedChip;
    public Button fillShelvesButton;
    public Button quickSaveButton;
    public Button storesButton;
    public Button settingsButton;
    public Button playButton;

    [Header("Tool Palette")]
    public ToolButton[] toolButtons;
    public SB_Panel placingBanner;
    public TMP_Text placingTitleText;
    public TMP_Text placingHintText;
    public GameObject placingRotateHint;
    public TMP_Text placingCancelText;

    [Header("Status Bar")]
    public TMP_Text statusHintText;
    public TMP_Text statusInfoText;

    [Header("Store Inspector")]
    public SB_Panel storeInspector;
    public TMP_InputField storeWidthInput;
    public TMP_InputField storeDepthInput;
    public TMP_InputField wallHeightInput;
    public SB_Segmented streetWallSegment;
    public SB_Segmented exitDoorTypeSegment;
    public SB_Segmented exitDoorPositionSegment;
    public SB_StatusRow readyDoorRow;
    public SB_StatusRow readyFixturesRow;
    public SB_StatusRow readyAgentRow;
    public Button placeAgentSpawnButton;

    [Header("Shelf Inspector")]
    public SB_Panel shelfInspector;
    public TMP_Text shelfTitleText;
    public TMP_Text shelfSubtitleText;
    public SB_ActionBar shelfActions;
    public SB_Segmented shelfTabs;
    public GameObject shelfLayoutTab;
    public GameObject shelfItemsTab;
    public TMP_Dropdown shelfCategoryDropdown;
    public Button applyShelfCategoryButton;
    public Toggle priceTagToggle;
    public ShelfEditGroupHandler shelfEditGroupHandler;

    [Header("Level Category Inspector")]
    public SB_Panel subShelfInspector;
    public TMP_Text subShelfSubtitleText;
    public TMP_Dropdown itemCategoryDropdown;

    [Header("Prop Inspector")]
    public Button[] inspectorCloseButtons;
    public SB_Panel propInspector;
    public TMP_Text propTitleText;
    public SB_ActionBar propActions;

    [Header("Aisle Marker Inspector")]
    public SB_Panel aisleInspector;
    public SB_ActionBar aisleActions;
    public TMP_InputField aisleCategory1Input;
    public TMP_InputField aisleCategory2Input;
    public TMP_InputField aisleCategory3Input;
    public TMP_InputField aisleNumberInput;
    public TMP_InputField aisleCableLengthInput;

    [Header("Stores Dialog")]
    public SB_Panel storesDialog;
    public Button storesCloseButton;
    public Button storesScrimButton;
    public TMP_InputField storeSearchInput;
    public RectTransform storeListRoot;
    public SB_StoreRow storeRowTemplate;
    public TMP_Text storeListEmptyText;
    public Button openStoreButton;
    public TMP_Text openStoreLabel;
    public TMP_InputField saveStoreTextField;
    public GameObject overwriteWarning;
    public TMP_Text overwriteWarningText;
    public Button saveStoreButton;
    public TMP_Text saveStoreLabel;
    public SB_ButtonFx saveStoreFx;
    public Button showFolderButton;

    [Header("Settings Dialog")]
    public SB_Panel settingsDialog;
    public Button settingsCloseButton;
    public Button settingsScrimButton;
    public Button[] settingsTabButtons;
    public SB_ButtonFx[] settingsTabFx;
    public GameObject agentTab;
    public GameObject renderingTab;
    public SB_Segmented agentAvatarSegment;
    public SB_Segmented agentInteractionSegment;
    public SB_Segmented agentBasketSegment;
    public SB_Segmented scanningDifficultySegment;
    public SB_Segmented renderPresetSegment;
    public GameObject renderCustomChip;
    public Toggle textureArraysToggle;
    public TMP_Text textureArraysCostText;
    public Toggle indirectDrawToggle;
    public SB_Segmented textureResolutionSegment;
    public TMP_Text memoryCostText;

    private OutlineSelector _activeShelfSelector;
    private OutlineSelector _activePropSelector;
    private SubShelfMarker _activeSubShelf;

    // Mirrors the spawn-items toggle so overflow suppression can be undone cleanly
    private bool _userWantsSpawnItems;

    void Start()
    {
        FillEnumDropdown<ItemCategory>(shelfCategoryDropdown);
        FillEnumDropdown<ItemCategory>(itemCategoryDropdown);
        FillEnumDropdown<ItemSpawnOption>(shelfEditGroupHandler.itemSpawnOption, Humanize);

        storeNameInput.SetTextWithoutNotify(DataHandler.Instance.storeName);
        SyncRenderingSettings();
        BindControls();
        RefreshInspector();
        RefreshStatus();
        InvokeRepeating(nameof(RefreshStatus), 0.5f, 0.5f);
    }

    void Update()
    {
        StoreBuilderInput.Blocked = storesDialog.IsOpen || settingsDialog.IsOpen;
        if (StoreBuilderInput.Blocked && Input.GetKeyDown(KeyCode.Escape)) CloseDialogs();
        else if (StoreBuilderInput.Modifier && Input.GetKeyDown(KeyCode.S)) OnQuickSavePressed();

        UpdateToolState();
    }

    void OnDisable() => StoreBuilderInput.Blocked = false;

    // Replaces a dropdown's options with the names of enum T (or `label(value)` when given).
    static void FillEnumDropdown<T>(TMP_Dropdown dropdown, Func<T, string> label = null) where T : Enum
    {
        if (dropdown == null) return;
        dropdown.ClearOptions();
        var options = new List<string>();
        foreach (T value in Enum.GetValues(typeof(T)))
            options.Add(label != null ? label(value) : value.ToString());
        dropdown.AddOptions(options);
    }

    // "GenerateRandomThenSave" -> "Generate random then save".
    static string Humanize<T>(T value) where T : Enum
    {
        string spaced = Regex.Replace(value.ToString(), "(?<=[a-z])(?=[A-Z])", " ").ToLowerInvariant();
        return char.ToUpperInvariant(spaced[0]) + spaced.Substring(1);
    }

    static void Bind(Toggle toggle, Action<Toggle> handler)
    {
        if (toggle != null) toggle.onValueChanged.AddListener(_ => handler(toggle));
    }

    // Wires every control to its handler once, after the initial values were set without notification.
    void BindControls()
    {
        storeNameInput.onEndEdit.AddListener(OnStoreNameEdited);
        fillShelvesButton.onClick.AddListener(OnSpawnItemsOnAllShelvesButtonPressed);
        quickSaveButton.onClick.AddListener(OnQuickSavePressed);
        storesButton.onClick.AddListener(OpenStoresDialog);
        settingsButton.onClick.AddListener(OpenSettingsDialog);
        playButton.onClick.AddListener(OnSpawnIntoStorePressed);

        foreach (ToolButton tool in toolButtons)
        {
            BuilderTool id = tool.tool;
            tool.button.onClick.AddListener(() => interactionController.SelectTool(id));
        }
        placeAgentSpawnButton.onClick.AddListener(() => interactionController.SelectTool(BuilderTool.AgentSpawn));
        foreach (Button close in inspectorCloseButtons) close.onClick.AddListener(ClearSelection);

        BindStoreInspector();
        BindShelfInspector();
        BindAisleInspector();
        BindDialogs();

        shelfActions.Bind(interactionController);
        propActions.Bind(interactionController);
        aisleActions.Bind(interactionController);
    }
}
